/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Sitemap_indexDotxmlRouteImport } from './routes/sitemap_index[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapViDotxmlRouteImport } from './routes/sitemap-vi[.]xml'
import { Route as SitemapUkDotxmlRouteImport } from './routes/sitemap-uk[.]xml'
import { Route as SitemapTrDotxmlRouteImport } from './routes/sitemap-tr[.]xml'
import { Route as SitemapThDotxmlRouteImport } from './routes/sitemap-th[.]xml'
import { Route as SitemapRuDotxmlRouteImport } from './routes/sitemap-ru[.]xml'
import { Route as SitemapPtDotxmlRouteImport } from './routes/sitemap-pt[.]xml'
import { Route as SitemapPlDotxmlRouteImport } from './routes/sitemap-pl[.]xml'
import { Route as SitemapNlDotxmlRouteImport } from './routes/sitemap-nl[.]xml'
import { Route as SitemapJaDotxmlRouteImport } from './routes/sitemap-ja[.]xml'
import { Route as SitemapItDotxmlRouteImport } from './routes/sitemap-it[.]xml'
import { Route as SitemapIdDotxmlRouteImport } from './routes/sitemap-id[.]xml'
import { Route as SitemapHiDotxmlRouteImport } from './routes/sitemap-hi[.]xml'
import { Route as SitemapFrDotxmlRouteImport } from './routes/sitemap-fr[.]xml'
import { Route as SitemapEsDotxmlRouteImport } from './routes/sitemap-es[.]xml'
import { Route as SitemapEnDotxmlRouteImport } from './routes/sitemap-en[.]xml'
import { Route as SitemapArDotxmlRouteImport } from './routes/sitemap-ar[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InstagramStoryViewerDownloaderRouteImport } from './routes/instagram-story-viewer-downloader'
import { Route as InstagramStoryDownloaderRouteImport } from './routes/instagram-story-downloader'
import { Route as InstagramReelsDownloaderRouteImport } from './routes/instagram-reels-downloader'
import { Route as InstagramPhotoDownloaderRouteImport } from './routes/instagram-photo-downloader'
import { Route as InstagramMp3DownloaderRouteImport } from './routes/instagram-mp3-downloader'
import { Route as IgtvDownloaderRouteImport } from './routes/igtv-downloader'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleInstagramStoryViewerDownloaderRouteImport } from './routes/$locale/instagram-story-viewer-downloader'
import { Route as LocaleInstagramStoryDownloaderRouteImport } from './routes/$locale/instagram-story-downloader'
import { Route as LocaleInstagramReelsDownloaderRouteImport } from './routes/$locale/instagram-reels-downloader'
import { Route as LocaleInstagramPhotoDownloaderRouteImport } from './routes/$locale/instagram-photo-downloader'
import { Route as LocaleInstagramMp3DownloaderRouteImport } from './routes/$locale/instagram-mp3-downloader'
import { Route as LocaleIgtvDownloaderRouteImport } from './routes/$locale/igtv-downloader'
import { Route as LocaleGuideRouteImport } from './routes/$locale/guide'
import { Route as LocaleFaqRouteImport } from './routes/$locale/faq'
import { Route as LocaleDisclaimerRouteImport } from './routes/$locale/disclaimer'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap_indexDotxmlRoute = Sitemap_indexDotxmlRouteImport.update({
  id: '/sitemap_index.xml',
  path: '/sitemap_index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapViDotxmlRoute = SitemapViDotxmlRouteImport.update({
  id: '/sitemap-vi.xml',
  path: '/sitemap-vi.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapUkDotxmlRoute = SitemapUkDotxmlRouteImport.update({
  id: '/sitemap-uk.xml',
  path: '/sitemap-uk.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapTrDotxmlRoute = SitemapTrDotxmlRouteImport.update({
  id: '/sitemap-tr.xml',
  path: '/sitemap-tr.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapThDotxmlRoute = SitemapThDotxmlRouteImport.update({
  id: '/sitemap-th.xml',
  path: '/sitemap-th.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRuDotxmlRoute = SitemapRuDotxmlRouteImport.update({
  id: '/sitemap-ru.xml',
  path: '/sitemap-ru.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPtDotxmlRoute = SitemapPtDotxmlRouteImport.update({
  id: '/sitemap-pt.xml',
  path: '/sitemap-pt.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPlDotxmlRoute = SitemapPlDotxmlRouteImport.update({
  id: '/sitemap-pl.xml',
  path: '/sitemap-pl.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapNlDotxmlRoute = SitemapNlDotxmlRouteImport.update({
  id: '/sitemap-nl.xml',
  path: '/sitemap-nl.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapJaDotxmlRoute = SitemapJaDotxmlRouteImport.update({
  id: '/sitemap-ja.xml',
  path: '/sitemap-ja.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapItDotxmlRoute = SitemapItDotxmlRouteImport.update({
  id: '/sitemap-it.xml',
  path: '/sitemap-it.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIdDotxmlRoute = SitemapIdDotxmlRouteImport.update({
  id: '/sitemap-id.xml',
  path: '/sitemap-id.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapHiDotxmlRoute = SitemapHiDotxmlRouteImport.update({
  id: '/sitemap-hi.xml',
  path: '/sitemap-hi.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapFrDotxmlRoute = SitemapFrDotxmlRouteImport.update({
  id: '/sitemap-fr.xml',
  path: '/sitemap-fr.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEsDotxmlRoute = SitemapEsDotxmlRouteImport.update({
  id: '/sitemap-es.xml',
  path: '/sitemap-es.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEnDotxmlRoute = SitemapEnDotxmlRouteImport.update({
  id: '/sitemap-en.xml',
  path: '/sitemap-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapArDotxmlRoute = SitemapArDotxmlRouteImport.update({
  id: '/sitemap-ar.xml',
  path: '/sitemap-ar.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramStoryViewerDownloaderRoute =
  InstagramStoryViewerDownloaderRouteImport.update({
    id: '/instagram-story-viewer-downloader',
    path: '/instagram-story-viewer-downloader',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstagramStoryDownloaderRoute =
  InstagramStoryDownloaderRouteImport.update({
    id: '/instagram-story-downloader',
    path: '/instagram-story-downloader',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstagramReelsDownloaderRoute =
  InstagramReelsDownloaderRouteImport.update({
    id: '/instagram-reels-downloader',
    path: '/instagram-reels-downloader',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstagramPhotoDownloaderRoute =
  InstagramPhotoDownloaderRouteImport.update({
    id: '/instagram-photo-downloader',
    path: '/instagram-photo-downloader',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstagramMp3DownloaderRoute = InstagramMp3DownloaderRouteImport.update({
  id: '/instagram-mp3-downloader',
  path: '/instagram-mp3-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const IgtvDownloaderRoute = IgtvDownloaderRouteImport.update({
  id: '/igtv-downloader',
  path: '/igtv-downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInstagramStoryViewerDownloaderRoute =
  LocaleInstagramStoryViewerDownloaderRouteImport.update({
    id: '/instagram-story-viewer-downloader',
    path: '/instagram-story-viewer-downloader',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleInstagramStoryDownloaderRoute =
  LocaleInstagramStoryDownloaderRouteImport.update({
    id: '/instagram-story-downloader',
    path: '/instagram-story-downloader',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleInstagramReelsDownloaderRoute =
  LocaleInstagramReelsDownloaderRouteImport.update({
    id: '/instagram-reels-downloader',
    path: '/instagram-reels-downloader',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleInstagramPhotoDownloaderRoute =
  LocaleInstagramPhotoDownloaderRouteImport.update({
    id: '/instagram-photo-downloader',
    path: '/instagram-photo-downloader',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleInstagramMp3DownloaderRoute =
  LocaleInstagramMp3DownloaderRouteImport.update({
    id: '/instagram-mp3-downloader',
    path: '/instagram-mp3-downloader',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleIgtvDownloaderRoute = LocaleIgtvDownloaderRouteImport.update({
  id: '/igtv-downloader',
  path: '/igtv-downloader',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuideRoute = LocaleGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDisclaimerRoute = LocaleDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/igtv-downloader': typeof IgtvDownloaderRoute
  '/instagram-mp3-downloader': typeof InstagramMp3DownloaderRoute
  '/instagram-photo-downloader': typeof InstagramPhotoDownloaderRoute
  '/instagram-reels-downloader': typeof InstagramReelsDownloaderRoute
  '/instagram-story-downloader': typeof InstagramStoryDownloaderRoute
  '/instagram-story-viewer-downloader': typeof InstagramStoryViewerDownloaderRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-fr.xml': typeof SitemapFrDotxmlRoute
  '/sitemap-hi.xml': typeof SitemapHiDotxmlRoute
  '/sitemap-id.xml': typeof SitemapIdDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ja.xml': typeof SitemapJaDotxmlRoute
  '/sitemap-nl.xml': typeof SitemapNlDotxmlRoute
  '/sitemap-pl.xml': typeof SitemapPlDotxmlRoute
  '/sitemap-pt.xml': typeof SitemapPtDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-th.xml': typeof SitemapThDotxmlRoute
  '/sitemap-tr.xml': typeof SitemapTrDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap-vi.xml': typeof SitemapViDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/igtv-downloader': typeof LocaleIgtvDownloaderRoute
  '/$locale/instagram-mp3-downloader': typeof LocaleInstagramMp3DownloaderRoute
  '/$locale/instagram-photo-downloader': typeof LocaleInstagramPhotoDownloaderRoute
  '/$locale/instagram-reels-downloader': typeof LocaleInstagramReelsDownloaderRoute
  '/$locale/instagram-story-downloader': typeof LocaleInstagramStoryDownloaderRoute
  '/$locale/instagram-story-viewer-downloader': typeof LocaleInstagramStoryViewerDownloaderRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/igtv-downloader': typeof IgtvDownloaderRoute
  '/instagram-mp3-downloader': typeof InstagramMp3DownloaderRoute
  '/instagram-photo-downloader': typeof InstagramPhotoDownloaderRoute
  '/instagram-reels-downloader': typeof InstagramReelsDownloaderRoute
  '/instagram-story-downloader': typeof InstagramStoryDownloaderRoute
  '/instagram-story-viewer-downloader': typeof InstagramStoryViewerDownloaderRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-fr.xml': typeof SitemapFrDotxmlRoute
  '/sitemap-hi.xml': typeof SitemapHiDotxmlRoute
  '/sitemap-id.xml': typeof SitemapIdDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ja.xml': typeof SitemapJaDotxmlRoute
  '/sitemap-nl.xml': typeof SitemapNlDotxmlRoute
  '/sitemap-pl.xml': typeof SitemapPlDotxmlRoute
  '/sitemap-pt.xml': typeof SitemapPtDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-th.xml': typeof SitemapThDotxmlRoute
  '/sitemap-tr.xml': typeof SitemapTrDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap-vi.xml': typeof SitemapViDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/igtv-downloader': typeof LocaleIgtvDownloaderRoute
  '/$locale/instagram-mp3-downloader': typeof LocaleInstagramMp3DownloaderRoute
  '/$locale/instagram-photo-downloader': typeof LocaleInstagramPhotoDownloaderRoute
  '/$locale/instagram-reels-downloader': typeof LocaleInstagramReelsDownloaderRoute
  '/$locale/instagram-story-downloader': typeof LocaleInstagramStoryDownloaderRoute
  '/$locale/instagram-story-viewer-downloader': typeof LocaleInstagramStoryViewerDownloaderRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/igtv-downloader': typeof IgtvDownloaderRoute
  '/instagram-mp3-downloader': typeof InstagramMp3DownloaderRoute
  '/instagram-photo-downloader': typeof InstagramPhotoDownloaderRoute
  '/instagram-reels-downloader': typeof InstagramReelsDownloaderRoute
  '/instagram-story-downloader': typeof InstagramStoryDownloaderRoute
  '/instagram-story-viewer-downloader': typeof InstagramStoryViewerDownloaderRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-ar.xml': typeof SitemapArDotxmlRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-fr.xml': typeof SitemapFrDotxmlRoute
  '/sitemap-hi.xml': typeof SitemapHiDotxmlRoute
  '/sitemap-id.xml': typeof SitemapIdDotxmlRoute
  '/sitemap-it.xml': typeof SitemapItDotxmlRoute
  '/sitemap-ja.xml': typeof SitemapJaDotxmlRoute
  '/sitemap-nl.xml': typeof SitemapNlDotxmlRoute
  '/sitemap-pl.xml': typeof SitemapPlDotxmlRoute
  '/sitemap-pt.xml': typeof SitemapPtDotxmlRoute
  '/sitemap-ru.xml': typeof SitemapRuDotxmlRoute
  '/sitemap-th.xml': typeof SitemapThDotxmlRoute
  '/sitemap-tr.xml': typeof SitemapTrDotxmlRoute
  '/sitemap-uk.xml': typeof SitemapUkDotxmlRoute
  '/sitemap-vi.xml': typeof SitemapViDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/disclaimer': typeof LocaleDisclaimerRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/guide': typeof LocaleGuideRoute
  '/$locale/igtv-downloader': typeof LocaleIgtvDownloaderRoute
  '/$locale/instagram-mp3-downloader': typeof LocaleInstagramMp3DownloaderRoute
  '/$locale/instagram-photo-downloader': typeof LocaleInstagramPhotoDownloaderRoute
  '/$locale/instagram-reels-downloader': typeof LocaleInstagramReelsDownloaderRoute
  '/$locale/instagram-story-downloader': typeof LocaleInstagramStoryDownloaderRoute
  '/$locale/instagram-story-viewer-downloader': typeof LocaleInstagramStoryViewerDownloaderRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/guide'
    | '/igtv-downloader'
    | '/instagram-mp3-downloader'
    | '/instagram-photo-downloader'
    | '/instagram-reels-downloader'
    | '/instagram-story-downloader'
    | '/instagram-story-viewer-downloader'
    | '/privacy'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-fr.xml'
    | '/sitemap-hi.xml'
    | '/sitemap-id.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ja.xml'
    | '/sitemap-nl.xml'
    | '/sitemap-pl.xml'
    | '/sitemap-pt.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-th.xml'
    | '/sitemap-tr.xml'
    | '/sitemap-uk.xml'
    | '/sitemap-vi.xml'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/terms'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/disclaimer'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/igtv-downloader'
    | '/$locale/instagram-mp3-downloader'
    | '/$locale/instagram-photo-downloader'
    | '/$locale/instagram-reels-downloader'
    | '/$locale/instagram-story-downloader'
    | '/$locale/instagram-story-viewer-downloader'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/guide'
    | '/igtv-downloader'
    | '/instagram-mp3-downloader'
    | '/instagram-photo-downloader'
    | '/instagram-reels-downloader'
    | '/instagram-story-downloader'
    | '/instagram-story-viewer-downloader'
    | '/privacy'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-fr.xml'
    | '/sitemap-hi.xml'
    | '/sitemap-id.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ja.xml'
    | '/sitemap-nl.xml'
    | '/sitemap-pl.xml'
    | '/sitemap-pt.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-th.xml'
    | '/sitemap-tr.xml'
    | '/sitemap-uk.xml'
    | '/sitemap-vi.xml'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/terms'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/disclaimer'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/igtv-downloader'
    | '/$locale/instagram-mp3-downloader'
    | '/$locale/instagram-photo-downloader'
    | '/$locale/instagram-reels-downloader'
    | '/$locale/instagram-story-downloader'
    | '/$locale/instagram-story-viewer-downloader'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/guide'
    | '/igtv-downloader'
    | '/instagram-mp3-downloader'
    | '/instagram-photo-downloader'
    | '/instagram-reels-downloader'
    | '/instagram-story-downloader'
    | '/instagram-story-viewer-downloader'
    | '/privacy'
    | '/sitemap-ar.xml'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-fr.xml'
    | '/sitemap-hi.xml'
    | '/sitemap-id.xml'
    | '/sitemap-it.xml'
    | '/sitemap-ja.xml'
    | '/sitemap-nl.xml'
    | '/sitemap-pl.xml'
    | '/sitemap-pt.xml'
    | '/sitemap-ru.xml'
    | '/sitemap-th.xml'
    | '/sitemap-tr.xml'
    | '/sitemap-uk.xml'
    | '/sitemap-vi.xml'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/terms'
    | '/$locale/about'
    | '/$locale/contact'
    | '/$locale/disclaimer'
    | '/$locale/faq'
    | '/$locale/guide'
    | '/$locale/igtv-downloader'
    | '/$locale/instagram-mp3-downloader'
    | '/$locale/instagram-photo-downloader'
    | '/$locale/instagram-reels-downloader'
    | '/$locale/instagram-story-downloader'
    | '/$locale/instagram-story-viewer-downloader'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  GuideRoute: typeof GuideRoute
  IgtvDownloaderRoute: typeof IgtvDownloaderRoute
  InstagramMp3DownloaderRoute: typeof InstagramMp3DownloaderRoute
  InstagramPhotoDownloaderRoute: typeof InstagramPhotoDownloaderRoute
  InstagramReelsDownloaderRoute: typeof InstagramReelsDownloaderRoute
  InstagramStoryDownloaderRoute: typeof InstagramStoryDownloaderRoute
  InstagramStoryViewerDownloaderRoute: typeof InstagramStoryViewerDownloaderRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapArDotxmlRoute: typeof SitemapArDotxmlRoute
  SitemapEnDotxmlRoute: typeof SitemapEnDotxmlRoute
  SitemapEsDotxmlRoute: typeof SitemapEsDotxmlRoute
  SitemapFrDotxmlRoute: typeof SitemapFrDotxmlRoute
  SitemapHiDotxmlRoute: typeof SitemapHiDotxmlRoute
  SitemapIdDotxmlRoute: typeof SitemapIdDotxmlRoute
  SitemapItDotxmlRoute: typeof SitemapItDotxmlRoute
  SitemapJaDotxmlRoute: typeof SitemapJaDotxmlRoute
  SitemapNlDotxmlRoute: typeof SitemapNlDotxmlRoute
  SitemapPlDotxmlRoute: typeof SitemapPlDotxmlRoute
  SitemapPtDotxmlRoute: typeof SitemapPtDotxmlRoute
  SitemapRuDotxmlRoute: typeof SitemapRuDotxmlRoute
  SitemapThDotxmlRoute: typeof SitemapThDotxmlRoute
  SitemapTrDotxmlRoute: typeof SitemapTrDotxmlRoute
  SitemapUkDotxmlRoute: typeof SitemapUkDotxmlRoute
  SitemapViDotxmlRoute: typeof SitemapViDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Sitemap_indexDotxmlRoute: typeof Sitemap_indexDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap_index.xml': {
      id: '/sitemap_index.xml'
      path: '/sitemap_index.xml'
      fullPath: '/sitemap_index.xml'
      preLoaderRoute: typeof Sitemap_indexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-vi.xml': {
      id: '/sitemap-vi.xml'
      path: '/sitemap-vi.xml'
      fullPath: '/sitemap-vi.xml'
      preLoaderRoute: typeof SitemapViDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-uk.xml': {
      id: '/sitemap-uk.xml'
      path: '/sitemap-uk.xml'
      fullPath: '/sitemap-uk.xml'
      preLoaderRoute: typeof SitemapUkDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-tr.xml': {
      id: '/sitemap-tr.xml'
      path: '/sitemap-tr.xml'
      fullPath: '/sitemap-tr.xml'
      preLoaderRoute: typeof SitemapTrDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-th.xml': {
      id: '/sitemap-th.xml'
      path: '/sitemap-th.xml'
      fullPath: '/sitemap-th.xml'
      preLoaderRoute: typeof SitemapThDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ru.xml': {
      id: '/sitemap-ru.xml'
      path: '/sitemap-ru.xml'
      fullPath: '/sitemap-ru.xml'
      preLoaderRoute: typeof SitemapRuDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pt.xml': {
      id: '/sitemap-pt.xml'
      path: '/sitemap-pt.xml'
      fullPath: '/sitemap-pt.xml'
      preLoaderRoute: typeof SitemapPtDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pl.xml': {
      id: '/sitemap-pl.xml'
      path: '/sitemap-pl.xml'
      fullPath: '/sitemap-pl.xml'
      preLoaderRoute: typeof SitemapPlDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-nl.xml': {
      id: '/sitemap-nl.xml'
      path: '/sitemap-nl.xml'
      fullPath: '/sitemap-nl.xml'
      preLoaderRoute: typeof SitemapNlDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ja.xml': {
      id: '/sitemap-ja.xml'
      path: '/sitemap-ja.xml'
      fullPath: '/sitemap-ja.xml'
      preLoaderRoute: typeof SitemapJaDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-it.xml': {
      id: '/sitemap-it.xml'
      path: '/sitemap-it.xml'
      fullPath: '/sitemap-it.xml'
      preLoaderRoute: typeof SitemapItDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-id.xml': {
      id: '/sitemap-id.xml'
      path: '/sitemap-id.xml'
      fullPath: '/sitemap-id.xml'
      preLoaderRoute: typeof SitemapIdDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-hi.xml': {
      id: '/sitemap-hi.xml'
      path: '/sitemap-hi.xml'
      fullPath: '/sitemap-hi.xml'
      preLoaderRoute: typeof SitemapHiDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-fr.xml': {
      id: '/sitemap-fr.xml'
      path: '/sitemap-fr.xml'
      fullPath: '/sitemap-fr.xml'
      preLoaderRoute: typeof SitemapFrDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-es.xml': {
      id: '/sitemap-es.xml'
      path: '/sitemap-es.xml'
      fullPath: '/sitemap-es.xml'
      preLoaderRoute: typeof SitemapEsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-en.xml': {
      id: '/sitemap-en.xml'
      path: '/sitemap-en.xml'
      fullPath: '/sitemap-en.xml'
      preLoaderRoute: typeof SitemapEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-ar.xml': {
      id: '/sitemap-ar.xml'
      path: '/sitemap-ar.xml'
      fullPath: '/sitemap-ar.xml'
      preLoaderRoute: typeof SitemapArDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-story-viewer-downloader': {
      id: '/instagram-story-viewer-downloader'
      path: '/instagram-story-viewer-downloader'
      fullPath: '/instagram-story-viewer-downloader'
      preLoaderRoute: typeof InstagramStoryViewerDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-story-downloader': {
      id: '/instagram-story-downloader'
      path: '/instagram-story-downloader'
      fullPath: '/instagram-story-downloader'
      preLoaderRoute: typeof InstagramStoryDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-reels-downloader': {
      id: '/instagram-reels-downloader'
      path: '/instagram-reels-downloader'
      fullPath: '/instagram-reels-downloader'
      preLoaderRoute: typeof InstagramReelsDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-photo-downloader': {
      id: '/instagram-photo-downloader'
      path: '/instagram-photo-downloader'
      fullPath: '/instagram-photo-downloader'
      preLoaderRoute: typeof InstagramPhotoDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-mp3-downloader': {
      id: '/instagram-mp3-downloader'
      path: '/instagram-mp3-downloader'
      fullPath: '/instagram-mp3-downloader'
      preLoaderRoute: typeof InstagramMp3DownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igtv-downloader': {
      id: '/igtv-downloader'
      path: '/igtv-downloader'
      fullPath: '/igtv-downloader'
      preLoaderRoute: typeof IgtvDownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/instagram-story-viewer-downloader': {
      id: '/$locale/instagram-story-viewer-downloader'
      path: '/instagram-story-viewer-downloader'
      fullPath: '/$locale/instagram-story-viewer-downloader'
      preLoaderRoute: typeof LocaleInstagramStoryViewerDownloaderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/instagram-story-downloader': {
      id: '/$locale/instagram-story-downloader'
      path: '/instagram-story-downloader'
      fullPath: '/$locale/instagram-story-downloader'
      preLoaderRoute: typeof LocaleInstagramStoryDownloaderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/instagram-reels-downloader': {
      id: '/$locale/instagram-reels-downloader'
      path: '/instagram-reels-downloader'
      fullPath: '/$locale/instagram-reels-downloader'
      preLoaderRoute: typeof LocaleInstagramReelsDownloaderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/instagram-photo-downloader': {
      id: '/$locale/instagram-photo-downloader'
      path: '/instagram-photo-downloader'
      fullPath: '/$locale/instagram-photo-downloader'
      preLoaderRoute: typeof LocaleInstagramPhotoDownloaderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/instagram-mp3-downloader': {
      id: '/$locale/instagram-mp3-downloader'
      path: '/instagram-mp3-downloader'
      fullPath: '/$locale/instagram-mp3-downloader'
      preLoaderRoute: typeof LocaleInstagramMp3DownloaderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/igtv-downloader': {
      id: '/$locale/igtv-downloader'
      path: '/igtv-downloader'
      fullPath: '/$locale/igtv-downloader'
      preLoaderRoute: typeof LocaleIgtvDownloaderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guide': {
      id: '/$locale/guide'
      path: '/guide'
      fullPath: '/$locale/guide'
      preLoaderRoute: typeof LocaleGuideRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/disclaimer': {
      id: '/$locale/disclaimer'
      path: '/disclaimer'
      fullPath: '/$locale/disclaimer'
      preLoaderRoute: typeof LocaleDisclaimerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleDisclaimerRoute: typeof LocaleDisclaimerRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleGuideRoute: typeof LocaleGuideRoute
  LocaleIgtvDownloaderRoute: typeof LocaleIgtvDownloaderRoute
  LocaleInstagramMp3DownloaderRoute: typeof LocaleInstagramMp3DownloaderRoute
  LocaleInstagramPhotoDownloaderRoute: typeof LocaleInstagramPhotoDownloaderRoute
  LocaleInstagramReelsDownloaderRoute: typeof LocaleInstagramReelsDownloaderRoute
  LocaleInstagramStoryDownloaderRoute: typeof LocaleInstagramStoryDownloaderRoute
  LocaleInstagramStoryViewerDownloaderRoute: typeof LocaleInstagramStoryViewerDownloaderRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleDisclaimerRoute: LocaleDisclaimerRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleGuideRoute: LocaleGuideRoute,
  LocaleIgtvDownloaderRoute: LocaleIgtvDownloaderRoute,
  LocaleInstagramMp3DownloaderRoute: LocaleInstagramMp3DownloaderRoute,
  LocaleInstagramPhotoDownloaderRoute: LocaleInstagramPhotoDownloaderRoute,
  LocaleInstagramReelsDownloaderRoute: LocaleInstagramReelsDownloaderRoute,
  LocaleInstagramStoryDownloaderRoute: LocaleInstagramStoryDownloaderRoute,
  LocaleInstagramStoryViewerDownloaderRoute:
    LocaleInstagramStoryViewerDownloaderRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  GuideRoute: GuideRoute,
  IgtvDownloaderRoute: IgtvDownloaderRoute,
  InstagramMp3DownloaderRoute: InstagramMp3DownloaderRoute,
  InstagramPhotoDownloaderRoute: InstagramPhotoDownloaderRoute,
  InstagramReelsDownloaderRoute: InstagramReelsDownloaderRoute,
  InstagramStoryDownloaderRoute: InstagramStoryDownloaderRoute,
  InstagramStoryViewerDownloaderRoute: InstagramStoryViewerDownloaderRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapArDotxmlRoute: SitemapArDotxmlRoute,
  SitemapEnDotxmlRoute: SitemapEnDotxmlRoute,
  SitemapEsDotxmlRoute: SitemapEsDotxmlRoute,
  SitemapFrDotxmlRoute: SitemapFrDotxmlRoute,
  SitemapHiDotxmlRoute: SitemapHiDotxmlRoute,
  SitemapIdDotxmlRoute: SitemapIdDotxmlRoute,
  SitemapItDotxmlRoute: SitemapItDotxmlRoute,
  SitemapJaDotxmlRoute: SitemapJaDotxmlRoute,
  SitemapNlDotxmlRoute: SitemapNlDotxmlRoute,
  SitemapPlDotxmlRoute: SitemapPlDotxmlRoute,
  SitemapPtDotxmlRoute: SitemapPtDotxmlRoute,
  SitemapRuDotxmlRoute: SitemapRuDotxmlRoute,
  SitemapThDotxmlRoute: SitemapThDotxmlRoute,
  SitemapTrDotxmlRoute: SitemapTrDotxmlRoute,
  SitemapUkDotxmlRoute: SitemapUkDotxmlRoute,
  SitemapViDotxmlRoute: SitemapViDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Sitemap_indexDotxmlRoute: Sitemap_indexDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
